"""initial

Revision ID: 18072ffd834b
Revises: 
Create Date: 2026-03-23 14:03:39.964410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18072ffd834b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_roles'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('music',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('artista', sa.String(length=255), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('num_canciones', sa.Integer(), nullable=True),
    sa.Column('duracion', sa.String(length=20), nullable=True),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valoracion', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['music.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('music')
    op.drop_table('users')
    # ### end Alembic commands ###
